### ISSUE TITLE
Error: Cannot find module 'selenium-webdriver/testing'     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

### ISSUE THREAD

**Issue by sumitkumar19940808** [sridharbandi/Selenium-WebdriverJS-Mocha-Template#1]
Error: Cannot find module 'selenium-webdriver/testing'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)

**Comment by sridharbandi** [comment]
@sumitkumar19940808 Thanks for pointing the issue. I have updated it, now it is working fine.
You might be also interested in https://github.com/sridharbandi/Selenium-Javascript-Getting-Started-Examples
